

export const allComponentsConfig = [
  { id: 1, name: "Input Fields", src: "components/inputFields" },
  { id: 2, name: "OTP Inputs", src: "components/otps" },
  { id: 3, name: "Labels", src: "components/labes" },
  { id: 4, name: "Navbars", src: "components/navbars" },
  { id: 5, name: "Menus", src: "components/menus" },
  { id: 6, name: "Masonry Gallery", src: "components/masoraryGallery" },
  { id: 7, name: "Banners", src: "components/bantos" },
  { id: 8, name: "Button Groups", src: "components/buttongroups" },
  { id: 9, name: "CTA Sections", src: "components/ctas" },
  { id: 10, name: "Radio Groups", src: "components/radioGroups" },
  { id: 11, name: "Checkboxes", src: "components/checkboses" },
  { id: 12, name: "Tooltip", src: "components/tooltip" },
  { id: 13, name: "Sidebars", src: "components/sidebars" },
  { id: 14, name: "Modals", src: "components/models" },
  { id: 15, name: "Dropdowns", src: "components/dropdowns" },
  { id: 16, name: "Accordions", src: "components/accordions" },
  { id: 17, name: "Cards", src: "components/cards" },
  { id: 18, name: "Badges", src: "components/badges" },
  { id: 19, name: "Avatars", src: "components/avatars" },
  { id: 20, name: "Toasts", src: "components/toasts" },
  { id: 21, name: "Tables", src: "components/tables" },
  { id: 22, name: "Pagination", src: "components/pagination" },
  { id: 23, name: "Loaders", src: "components/loaders" },
  { id: 24, name: "Carousel", src: "components/carousel" },
  { id: 25, name: "Code Block", src: "components/codeBlock" },
  { id: 26, name: "Calendar", src: "components/calender" },
  { id: 27, name: "Tabs", src: "components/tabs" },
  { id: 28, name: "Forms", src: "components/forms" },
  { id: 29, name: "BackgroundPatterns", src: "components/backgroundPatterns" },
  { id: 30, name: "Pills", src: "components/pills" },
  { id: 31, name: "Tags", src: "components/tags" },
  { id: 32, name: "TypeWriterEffects", src: "components/TypeWriterEffects" },
];
